# Generated by Django 5.0.3 on 2024-03-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_reservation_date_alter_reservation_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='full_name',
        ),
    ]
